baseURL = 'https://albertorodriguez84.github.io/Hugo_md/'
defaultContentLanguage = 'es'
title = 'Práctica 1 DWES - Uso de Markdown'
theme =['relearn']



[Languages]
    [Languages.es]
        title = "Uso de Markdown"
        weight = 1
        languageName = "Español"
        ContentDir="/content/sp"
    [Languages.en]
        title = "Using Markdown"
        weight = 2
        languageName = "English"
        ContentDir="/content/"
   [Languages.fr]
        title = "Utiliser la démarque"
        weight = 3
        languageName = "Français"
        ContentDir="/content/"